Collabstronauts_Site/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('activities.urls')),
]

activities/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(r'^$', views.activity_list, name='activity_list'),
]

activities/models.py
from django.db import models

class Activity(models.Model): 
	
	Activity_Type_Choices = (
		('MZ', 'Moment of Zen'),
		('IB', 'Icebreaker'),
		('BR', 'Brainstorm'),
		('DC', 'Discussion'),
		('TB', 'Teambuilding'),
		)


	Space_Type_Choices= (
		('R', "Room"),
		('V', "Virtual"),
		)


	activity_name = models.CharField(max_length = 100)
	activity_type = models.CharField (
		max_length =2, 
		choices= Activity_Type_Choices, 
		default='Icebreaker')
	num_people = models.IntegerField()
	space_type = models.CharField(
		max_length=2, 
		choices = Space_Type_Choices, 
		default= 'Room') 
	## rating =
	activity_desc = models.TextField(max_length = 1000)
	variations = models.TextField(max_length = 250)

activities/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Activity

# Create your views here.
def activity_list(request):
  activities = Activity.objects.order_by('activity_name')
  return render(request, 'activities/activity_list.html', {'activities': activities})

activities/templates/activities/activity_list.html
<html>
  <head>
    <title>Collabstronauts</title>
  </head>
  <body>
    <div>
      <h1><a href="/">Collabstronauts</a></h1>
    </div>

    <hr>

    {% for activity in activities %}
      <div>
        <h1><a href="">{{ activity.activity_name }}</a></h1>
        <span>
          Activity type: {{ activity.get_activity_type_display }}
          <br>
          Number of people: {{ activity.num_people }}
          <br>
          Space type: {{ activity.get_space_type_display }}
        </span>
        <h2>Description:</h2>
        <p>{{ activity.activity_desc|safe|linebreaksbr }}</p>
        <h2>Variations:</h2>
        <p>{{ activity.variations|safe|linebreaksbr }}</p>
      </div>
      <hr>
    {% endfor %}
  </body>
</html>